#!/bin/bash
#notice: ubuntu must reconfig bash
#        sudo ln -sf /bin/bash /bin/sh
#bash_profile
unset USERNAME


#use bash_completion
#rpm -ivh http://www.caliban.org/files/redhat/RPMS/noarch/bash-completion-20060301-1.noarch.rpm
if [ "$PS1" ]
then
    if [ -r /etc/bash_completion ]
    then
        . /etc/bash_completion
    else
        echo "NEED TO CONFIG bash-completion!!!"
    fi
fi

# Gimme a huge history
#export HISTSIZE=50000
# Don't store duplicate lines in history
export HISTCONTROL=ignoreboth
# Apend to history instead of overwriting
shopt -s histappend
# Unify histories across screen sessions
PROMPT_COMMAND="$PROMPT_COMMAND;history -a; history -n"



# local variables
export PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/bin:~/bin
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib

export JAVA_HOME=/home/tscadmin/java/current
#export JRE_HOME=${JAVA_HOME}/jre

export CLASSPATH=$HADOOP_HOME/lib:$JAVA_HOME/lib:$JRE_HOME/lib

export PATH=$PATH:$HADOOP_HOME/bin:$JAVA_HOME/bin:$JRE_HOME/bin:$HIVE_HOME

#设置了Ls的目录颜色
export HOSTSHORT=`hostname`
export OS=`uname`;

#export LC_ALL='zh_CN.GBK'
export LC_ALL='en_US.UTF-8'
#export LANG='zh_CN.GBK'
export LANG='en_US.UTF-8'

export SVN_EDITOR=vim

#shell promaote and title.
PROMPT_COMMAND='echo -ne "\033]0;[${HOSTSHORT}:`basename $PWD`\$]${PWD}\007"'
PS1='[\u@\h:${YROOT_NAME}\w\$] '

#.bashrc
if [ -f /etc/bashrc ]; then 
        . /etc/bashrc
fi

#all aliases
ALIASES=`\ls ~/.*aliases`
for f in $ALIASES
do
  if [ -f $f ];then
     . $f
  fi
done

#all completion
ALIASES=`\ls ~/.*completion`
for f in $ALIASES
do
  if [ -f $f ];then
     . $f
  fi
done

