#!/bin/bash

alias gs='git status'
alias ga='git add '
alias gc='git commit -m'
alias gull='git pull'
alias gush='git push --all'
alias gsh='git show'
alias gl='git log'
alias gb='git branch'
alias gco='git checkout'
alias gd='git diff'
alias gd1='echo “git diff HEAD”; git diff HEAD'
alias gd2='git diff HEAD^"; git diff HEAD^'
