#!/bin/bash
export HADOOP_HOME=/home/tscadmin/hadoop/current
export HADOOP_ROOT=/home/tscadmin/hadoop/current

export HIVE_HOME=/home/tscadmin/hive/bin

#hadoop
alias hls='hadoop dfs -ls'
alias hlsr='hadoop dfs -lsr'
alias hdu='hadoop dfs -du'
alias hdus='hadoop dfs -dus'
alias hcount='hadoop dfs -count'
alias hmv='sudo -u tscadmin hadoop dfs -mv'
alias hcp='sudo -u tscadmin hadoop dfs -cp'
alias hrm='sudo -u tscadmin hadoop dfs -rm'
alias hrmr='sudo -u tscadmin hadoop dfs -rmr'
alias hexpunge='hadoop dfs -expunge'
alias hput='sudo -u tscadmin hadoop dfs -put'
alias hcopyFromLocal='hadoop dfs -copyFromLocal'
alias hmoveFromLocal='hadoop dfs -moveFromLocal'
alias hget='hadoop dfs -get'
alias hgetmerge='hadoop dfs -getmerge'
alias hcat='hadoop dfs -cat'
alias htext='hadoop dfs -text'
alias hcopyToLocal='hadoop dfs -copyToLocal'
alias hmoveToLocal='hadoop dfs -moveToLocal'
alias hmkdir='sudo -u tscadmin hadoop dfs -mkdir'
alias hsetrep='hadoop dfs -setrep'
alias htouchz='sudo -u tscadmin hadoop dfs -touchz'
alias htest='hadoop dfs -test'
alias hstat='hadoop dfs -stat'
alias htail='hadoop dfs -tail'
alias hchmod='hadoop dfs -chmod'
alias hchown='hadoop dfs -chown'
alias hchgrp='hadoop dfs -chgrp'
alias hhelp='hadoop dfs -help'
